### ISSUE TITLE
Part4: Create a Todo

### ISSUE THREAD

**Issue by atlansien** [atlansien/TODO_APP_WITH_EXPRESS_AND_MYSQL#7]
# 行うこと

## テストの作成
- [x] ←完了後チェック

### テスト内容
- [x] `title`を送らなかった場合エラーが返る(ステータスコード400)
- [x] `body`を送らなかった場合エラーが返る(ステータスコード400)
- [x] 適切なデータを送った場合、正常に動作する(ステータスコード200)
  - [x] 作成されたTodoには、適切にデータが入っている
  - [x] DB内には、新規作成されたTodo1件が格納されている

#### 追加

- [x] `completed`に`boolean`、また`number`以外の値を送った場合、エラーが返る(ステータスコード400)
- [x] `completed`に`0/1`以外の`number`型を値として送った場合、エラーが返る(ステータスコード400)

この時点ではテストはRED

## Todoを作成し、テーブルに挿入する
- [x] ←完了後チェック

- [x] クライアントからデータを会得する
  - ~~`body-parser`を使用~~
  - `express.json()`に変更
    - 変更しても動きに差がなかった
    - コード量を減らすため
    - データ量を減らすため
  - 会得するデータ: `title`、`body`

### 追加

  - [x] クライアントからデータを会得する
     - 会得するデータ: `completed`
        - デフォルトで`false`が入るよう設定されてあるので`req.body`で会得されなくてもエラーにはならない

#### `completed`に数字型が格納される問題
- [x] ←完了後チェック

本来なら、completedに格納される値は`boolean`のみでなければならないが、MySQLにboolean型がなく、代わりに`tityint(1)`が設定されています。これは0を`false`、1を`true`に変換してくれますが、その他の`±127`内の数字は数字のまま格納されます。

##### 解決策

~~`toBoolean`というメソッドを作成し、`true/false`を判別、それ以外の値は`undefind`に変換されるようにしました。
その後、`try-catch`の例外処理で、boolean以外(undefind)の値は格納されないようしました。~~

`req.body.completed`で渡されたデータを`if`を使い`boolean`か`undefind`でない場合はエラーを投げる様にしました。

- [x] テーブル`todos`に格納する
  - `transaction`を用いる
     - Sequelizeドキュメント: [Trancations](http://docs.sequelizejs.com/manual/transactions.html)
     - トランザクションとは: [Qiita:「トランザクション」とは何か？を超わかりやすく語ってみた！
](https://qiita.com/zd6ir7/items/6568b6c3efc5d6a13865)

## トランザクションとは

複数の処理を1つにまとめたもの。
トランザクションにまとめることで、全ての操作が成功しないと処理されない。
もし複数の中のひとつでもエラーが発生した場合、処理は全て取り消され、トランザクション実行前の状態に戻る(`ロールバック`)
トランザクションは、まとめた処理の中からひとつだけ実行するということはできない。

## テストの確認
- [x] ←完了後チェック

## 実際の動作確認
- [x] ←完了後チェック

- POSTMANで確認を行う
