### ISSUE TITLE
Part5: Update a Todo

### ISSUE THREAD

**Issue by atlansien** [atlansien/TODO_APP_WITH_EXPRESS_AND_MYSQL#9]
# UpdateTodoメソッド

IDからTodoを検索し、会得したTodoの内容を書き換え、更新する。
更新するデータは`title`、`body`、`bool`の内どれかのみでも良い

- 検索方法
  - クエリーパラメータから検索する

## テストの作成

- [x] ←完了後チェック

### テスト内容

- [x] idの引数に不正な値が入っていた場合、エラーが返る
  - idの引数は`1以上`の整数でなければならない
  - 不正な値: 0以下の数字、文字列、真偽値、null、undefined、配列、オブジェクト

- [x] idの引数と合致するTodoがない場合、エラーが返る。

- [x] completedにboolean以外のデータ型を送った場合、エラーが返る

- [x] 適切なデータを渡した場合、適切な挙動を行う
  - [x] idの引数と合致したTodo１件の`title`、`body`、または両方が変更され、返される。
  - [x] 返されたTodo１件はDB内でも変更され、格納されている。
  - [x] 変更されたTodo１件の`updatedAt`は更新されている

この時点でテストはRED

## updateTodoの作成
- [x] ←完了後チェック

- [x] クライアントからデータを会得する
  - [x] `id`
     - クエリーパラメータを使用する
  - [x] `title`、`body`、`completed`
     - express.json()を使用する
     - 全て入力する必要はない

## テストの確認
- [x] ←完了後チェック

### テスト内容

- [x] idの引数に不正な値が入っていた場合、エラーが返る
  - idの引数は数字でなければならない
  - 不正な値: 文字列、真偽値、null、undefined、配列、オブジェクト

- [x] idの引数と合致するTodoがない場合、エラーが返る。

- [x] completedにboolean以外のデータ型を送った場合、エラーが返る

- [x] 適切なデータを渡した場合、適切な挙動を行う
  - [x] idの引数と合致したTodo１件の`title`、`body`、または両方が変更され、返される。
  - [x] 返されたTodo１件はDB内でも変更され、格納されている。
  - [x] 変更されたTodo１件の`updatedAt`は更新されている

## 実際の動作確認
- [x] ←完了後チェック

- POSTMANにて確認
